export default {
  ON_ADDITIONAL_FETCHING: "ON_ADDITIONAL_FETCHING",
  ON_ADDITIONAL_SUCCESS: "ON_ADDITIONAL_SUCCESS",
  ON_ADDITIONAL_FAILED: "ON_ADDITIONAL_FAILED",
  ADD_ADDITIONAL: "ADD_ADDITIONAL"
};
