export default {
    ON_CINEMA_FETCHING: "ON_CINEMA_FETCHING",
    ON_LOAD_CINEMA_SUCCESS: "ON_LOAD_CINEMA_SUCCESS",
    ON_LOAD_CINEMA_FAILED: "ON_LOAD_CINEMA_FAILED",

    ON_CINEMA_PAGE_CHANGE: "ON_CINEMA_PAGE_CHANGE",

    ON_ADD_CINEMA_SUCCESS: "ON_ADD_CINEMA_SUCCESS",
    ON_ADD_CINEMA_FAILED: "ON_ADD_CINEMA_FAILED",
};