export default {
  ON_FILMS_FETCHING: "ON_FILMS_FETCHING",
  ON_ADD_NEW_FILM_SUCCESS: "ON_ADD_NEW_FILM_SUCCESS",
  ON_ADD_NEW_FILM_FAILED: "ON_ADD_NEW_FILM_FAILED",

  ON_PAGE_ID_CHANGE: "ON_PAGE_ID_CHANGE",

  ON_LOAD_FILMS_SUCCESS: "ON_LOAD_FILMS_SUCCESS",
  ON_LOAD_FILMS_FAILED: "ON_LOAD_FILMS_FAILED",

  ON_SELECTED_FILM_CHANGE: "ON_SELECTED_FILM_CHANGE",

  ON_RESET_SELECTED_FILM: "ON_RESET_SELECTED_FILM"
};
