export default {
    ON_ADD_NEW_FILM_FETCHING: "ON_ADD_NEW_FILM_FETCHING",
    ON_ADD_NEW_FILM_SUCCESS: "ON_ADD_NEW_FILM_SUCCESS",
    ON_ADD_NEW_FILM_FAILED: "ON_ADD_NEW_FILM_FAILED",
    ADD_NEW_FILM: "ON_ADD_NEW_FILM",
};