export default {
    ON_FILMS_FILTER_CHANGE: "ON_FILMS_FILTER_CHANGE",
    ON_FILMS_PAGE_CHANGE: "ON_FILMS_PAGE_CHANGE",
    ON_FILMS_FETCHING: "ON_FILMS_FETCHING",
    ON_FILMS_FAILED: "ON_FILMS_FAILED",
    ON_FILMS_SUCCESS: "ON_FILMS_SUCCESS",
    ON_FILMS_CHANGE: "ON_FILMS_CHANGE",
};