// Note: https://www.npmjs.com/search?q=keymirror
export default {
    ON_SET_INITIAL_STATE: "ON_SET_INITIAL_STATE",
    ON_FILMS_FILTER_CHANGE: "ON_FILMS_FILTER_CHANGE",
    ON_FILMS_PAGE_CHANGE: "ON_FILMS_PAGE_CHANGE",
    ON_FILMS_FETCHING: "ON_FILMS_FETCHING",
    ON_FILMS_FAILED: "ON_FILMS_FAILED",
    ON_FILMS_SUCCESS: "ON_FILMS_SUCCESS",
    ON_FILM_SUCCESS: "ON_FILM_SUCCESS",
    ON_FILMS_CHANGE: "ON_FILMS_CHANGE",
    ON_SEARCH_TEXT_CHANGE: "ON_SEARCH_TEXT_CHANGE",
};