export default {
  ON_OPEN: "ON_OPEN",
  ON_CLOSE: "ON_CLOSE",
  ON_ADDITIONAL_FETCHING: "ON_ADDITIONAL_FETCHING",
  ON_ADDITIONAL_SUCCESS: "ON_ADDITIONAL_SUCCESS",
  ON_ADDITIONAL_FAILED: "ON_ADDITIONAL_FAILED",
  ON_SELECTED_PLACE_CHANGED: "ON_SELECTED_PLACE_CHANGED",
  ON_SELECTED_ADDITIONAL_ADD: "ON_SELECTED_ADDITIONAL_ADD",
  ON_SELECTED_ADDITIONAL_REMOVE: "ON_SELECTED_ADDITIONAL_REMOVE",
  ON_ORDER_SUCCESS: "ON_ORDER_SUCCESS"
};
