export default {
  ON_CHANGE_ORDER_SORT_FILTER: "ON_CHANGE_ORDER_SORT_FILTER",
  ON_ORDERS_FETCHING: "ON_ORDERS_FETCHING",
  ON_ORDERS_FAILED: "ON_ORDERS_FAILED",
  ON_ORDERS_SUCCESS: "ON_ORDERS_SUCCESS"
};
