export default {
    ON_USER_AUTH_STATUS_CHANGE: "ON_USER_AUTH_STATUS_CHANGE",
    ON_FETCH: "ON_FETCH",
    ON_LOGIN_OR_REGISTER_FAILED: "ON_LOGIN_OR_REGISTER_FAILED",
    ON_LOGIN_OR_REGISTER_SUCCESS: "ON_LOGIN_OR_REGISTER_SUCCESS",
    ON_LOGIN: "ON_LOGIN",
    ON_REGISTER: "ON_REGISTER",
    ON_LOGOUT: "ON_LOGOUT",
};